### ISSUE TITLE
Listing items with undefined currency

### ISSUE THREAD

**Issue by nischal-shetty2** [shopstr-eng/shopstr#77]
![Screenshot 2024-08-27 at 11 45 25 PM](https://github.com/user-attachments/assets/aab66801-7eac-47c5-aee6-3079ece7071a)

people are listing items with currency selected as undefined. i dont know how to reproduce this

**Comment by calvadev** [comment]
It's not possible to list items with an undefined currency from Shopstr itself. Those are being listed from other Nostr clients, most likely Amethyst or Coracle.
