### ISSUE TITLE
Enable auto-complete on dropdown 

### ISSUE THREAD

**Issue by humble-GOAT** [shopstr-eng/shopstr#81]
Hi,

It takes a loooong time to manually scroll and select my desired country from the location dropdown. Can we please make it possible to type and autocomplete?

![image](https://github.com/user-attachments/assets/c51ab8f1-f754-42e0-b996-d5d2120dd417)

**Comment by calvadev** [comment]
Sure! I'll work on adding searchable locations and categories within the next week or so in a minor release.

**Comment by calvadev** [comment]
@humble-GOAT You should be able to search now on mobile and desktop! It doesn't visually change the search bar, however, but it is working in the background. I can add some visual feedback to not confuse users as well.

**Comment by humble-GOAT** [comment]
Thank you, it works.
